//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : d8u6uelvine6d6
	/// Data Source    : ec2-54-217-202-110.eu-west-1.compute.amazonaws.com
	/// Server Version : 9.4.1
	/// </summary>
	public partial class dbContext : LinqToDB.Data.DataConnection
	{
		public ITable<auth_group>                 auth_group                 { get { return this.GetTable<auth_group>(); } }
		public ITable<auth_group_permissions>     auth_group_permissions     { get { return this.GetTable<auth_group_permissions>(); } }
		public ITable<auth_permission>            auth_permission            { get { return this.GetTable<auth_permission>(); } }
		public ITable<auth_user>                  auth_user                  { get { return this.GetTable<auth_user>(); } }
		public ITable<auth_user_groups>           auth_user_groups           { get { return this.GetTable<auth_user_groups>(); } }
		public ITable<auth_user_user_permissions> auth_user_user_permissions { get { return this.GetTable<auth_user_user_permissions>(); } }
		public ITable<django_admin_log>           django_admin_log           { get { return this.GetTable<django_admin_log>(); } }
		public ITable<django_content_type>        django_content_type        { get { return this.GetTable<django_content_type>(); } }
		public ITable<django_migrations>          django_migrations          { get { return this.GetTable<django_migrations>(); } }
		public ITable<django_session>             django_session             { get { return this.GetTable<django_session>(); } }
		public ITable<genre>                      genres                     { get { return this.GetTable<genre>(); } }
		public ITable<movie>                      movies                     { get { return this.GetTable<movie>(); } }
		public ITable<movie_genre>                movie_genre                { get { return this.GetTable<movie_genre>(); } }
		public ITable<person>                     people                     { get { return this.GetTable<person>(); } }
		public ITable<play_evolutions>            play_evolutions            { get { return this.GetTable<play_evolutions>(); } }
		public ITable<schema_migrations>          schema_migrations          { get { return this.GetTable<schema_migrations>(); } }

		public dbContext()
		{
			InitDataContext();
		}

		public dbContext(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table(Schema="public", Name="auth_group")]
	public partial class auth_group
	{
		[PrimaryKey, Identity] public int    id   { get; set; } // integer
		[Column,     NotNull ] public string name { get; set; } // character varying(80)

		#region Associations

		/// <summary>
		/// auth_group_permissio_group_id_689710a9a73b7457_fk_auth_group_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="group_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<auth_group_permissions> authgrouppermissiogroupid689710a9a73b7457fkauthgroupid { get; set; }

		/// <summary>
		/// auth_user_groups_group_id_33ac548dcf5f8e37_fk_auth_group_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="group_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<auth_user_groups> authusergroupsgroupid33ac548dcf5f8e37fkauthgroupid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="auth_group_permissions")]
	public partial class auth_group_permissions
	{
		[PrimaryKey, Identity] public int id            { get; set; } // integer
		[Column,     NotNull ] public int group_id      { get; set; } // integer
		[Column,     NotNull ] public int permission_id { get; set; } // integer

		#region Associations

		/// <summary>
		/// auth_group_permissio_group_id_689710a9a73b7457_fk_auth_group_id
		/// </summary>
		[Association(ThisKey="group_id", OtherKey="id", CanBeNull=false, KeyName="auth_group_permissio_group_id_689710a9a73b7457_fk_auth_group_id", BackReferenceName="authgrouppermissiogroupid689710a9a73b7457fkauthgroupid")]
		public auth_group authgrouppermissiogroupid689710a9a73b7457fkauthgroupid { get; set; }

		/// <summary>
		/// auth_group_permission_id_1f49ccbbdc69d2fc_fk_auth_permission_id
		/// </summary>
		[Association(ThisKey="permission_id", OtherKey="id", CanBeNull=false, KeyName="auth_group_permission_id_1f49ccbbdc69d2fc_fk_auth_permission_id", BackReferenceName="authgrouppermissionid1f49ccbbdc69d2fcfkauthpermissionid")]
		public auth_permission authgrouppermissionid1f49ccbbdc69d2fcfkauthpermissionid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="auth_permission")]
	public partial class auth_permission
	{
		[PrimaryKey, Identity] public int    id              { get; set; } // integer
		[Column,     NotNull ] public string name            { get; set; } // character varying(255)
		[Column,     NotNull ] public int    content_type_id { get; set; } // integer
		[Column,     NotNull ] public string codename        { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// auth_content_type_id_508cf46651277a81_fk_django_content_type_id
		/// </summary>
		[Association(ThisKey="content_type_id", OtherKey="id", CanBeNull=false, KeyName="auth_content_type_id_508cf46651277a81_fk_django_content_type_id", BackReferenceName="authcontenttypeid508cf46651277a81fkdjangocontenttypeid")]
		public django_content_type authcontenttypeid508cf46651277a81fkdjangocontenttypeid { get; set; }

		/// <summary>
		/// auth_group_permission_id_1f49ccbbdc69d2fc_fk_auth_permission_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="permission_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<auth_group_permissions> authgrouppermissionid1f49ccbbdc69d2fcfkauthpermissionid { get; set; }

		/// <summary>
		/// auth_user__permission_id_384b62483d7071f0_fk_auth_permission_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="permission_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<auth_user_user_permissions> authuserpermissionid384b62483d7071f0fkauthpermissionid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="auth_user")]
	public partial class auth_user
	{
		[PrimaryKey, Identity   ] public int             id           { get; set; } // integer
		[Column,     NotNull    ] public string          password     { get; set; } // character varying(128)
		[Column,        Nullable] public DateTimeOffset? last_login   { get; set; } // timestamp (6) with time zone
		[Column,     NotNull    ] public bool            is_superuser { get; set; } // boolean
		[Column,     NotNull    ] public string          username     { get; set; } // character varying(30)
		[Column,     NotNull    ] public string          first_name   { get; set; } // character varying(30)
		[Column,     NotNull    ] public string          last_name    { get; set; } // character varying(30)
		[Column,     NotNull    ] public string          email        { get; set; } // character varying(254)
		[Column,     NotNull    ] public bool            is_staff     { get; set; } // boolean
		[Column,     NotNull    ] public bool            is_active    { get; set; } // boolean
		[Column,     NotNull    ] public DateTimeOffset  date_joined  { get; set; } // timestamp (6) with time zone

		#region Associations

		/// <summary>
		/// auth_user_groups_user_id_4b5ed4ffdb8fd9b0_fk_auth_user_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="user_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<auth_user_groups> authusergroupsuserid4b5ed4ffdb8fd9b0fkauthuserid { get; set; }

		/// <summary>
		/// auth_user_user_permiss_user_id_7f0938558328534a_fk_auth_user_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="user_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<auth_user_user_permissions> authuseruserpermissuserid7f0938558328534afkauthuserid { get; set; }

		/// <summary>
		/// django_admin_log_user_id_52fdd58701c5f563_fk_auth_user_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="user_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<django_admin_log> djangoadminloguserid52fdd58701c5f563fkauthuserid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="auth_user_groups")]
	public partial class auth_user_groups
	{
		[PrimaryKey, Identity] public int id       { get; set; } // integer
		[Column,     NotNull ] public int user_id  { get; set; } // integer
		[Column,     NotNull ] public int group_id { get; set; } // integer

		#region Associations

		/// <summary>
		/// auth_user_groups_group_id_33ac548dcf5f8e37_fk_auth_group_id
		/// </summary>
		[Association(ThisKey="group_id", OtherKey="id", CanBeNull=false, KeyName="auth_user_groups_group_id_33ac548dcf5f8e37_fk_auth_group_id", BackReferenceName="authusergroupsgroupid33ac548dcf5f8e37fkauthgroupid")]
		public auth_group authusergroupsgroupid33ac548dcf5f8e37fkauthgroupid { get; set; }

		/// <summary>
		/// auth_user_groups_user_id_4b5ed4ffdb8fd9b0_fk_auth_user_id
		/// </summary>
		[Association(ThisKey="user_id", OtherKey="id", CanBeNull=false, KeyName="auth_user_groups_user_id_4b5ed4ffdb8fd9b0_fk_auth_user_id", BackReferenceName="authusergroupsuserid4b5ed4ffdb8fd9b0fkauthuserid")]
		public auth_user authusergroupsuserid4b5ed4ffdb8fd9b0fkauthuserid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="auth_user_user_permissions")]
	public partial class auth_user_user_permissions
	{
		[PrimaryKey, Identity] public int id            { get; set; } // integer
		[Column,     NotNull ] public int user_id       { get; set; } // integer
		[Column,     NotNull ] public int permission_id { get; set; } // integer

		#region Associations

		/// <summary>
		/// auth_user__permission_id_384b62483d7071f0_fk_auth_permission_id
		/// </summary>
		[Association(ThisKey="permission_id", OtherKey="id", CanBeNull=false, KeyName="auth_user__permission_id_384b62483d7071f0_fk_auth_permission_id", BackReferenceName="authuserpermissionid384b62483d7071f0fkauthpermissionid")]
		public auth_permission authuserpermissionid384b62483d7071f0fkauthpermissionid { get; set; }

		/// <summary>
		/// auth_user_user_permiss_user_id_7f0938558328534a_fk_auth_user_id
		/// </summary>
		[Association(ThisKey="user_id", OtherKey="id", CanBeNull=false, KeyName="auth_user_user_permiss_user_id_7f0938558328534a_fk_auth_user_id", BackReferenceName="authuseruserpermissuserid7f0938558328534afkauthuserid")]
		public auth_user authuseruserpermissuserid7f0938558328534afkauthuserid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="django_admin_log")]
	public partial class django_admin_log
	{
		[PrimaryKey, Identity   ] public int            id              { get; set; } // integer
		[Column,     NotNull    ] public DateTimeOffset action_time     { get; set; } // timestamp (6) with time zone
		[Column,        Nullable] public string         object_id       { get; set; } // text
		[Column,     NotNull    ] public string         object_repr     { get; set; } // character varying(200)
		[Column,     NotNull    ] public short          action_flag     { get; set; } // smallint
		[Column,     NotNull    ] public string         change_message  { get; set; } // text
		[Column,        Nullable] public int?           content_type_id { get; set; } // integer
		[Column,     NotNull    ] public int            user_id         { get; set; } // integer

		#region Associations

		/// <summary>
		/// djan_content_type_id_697914295151027a_fk_django_content_type_id
		/// </summary>
		[Association(ThisKey="content_type_id", OtherKey="id", CanBeNull=true, KeyName="djan_content_type_id_697914295151027a_fk_django_content_type_id", BackReferenceName="djancontenttypeid697914295151027afkdjangocontenttypeid")]
		public django_content_type djancontenttypeid697914295151027afkdjangocontenttypeid { get; set; }

		/// <summary>
		/// django_admin_log_user_id_52fdd58701c5f563_fk_auth_user_id
		/// </summary>
		[Association(ThisKey="user_id", OtherKey="id", CanBeNull=false, KeyName="django_admin_log_user_id_52fdd58701c5f563_fk_auth_user_id", BackReferenceName="djangoadminloguserid52fdd58701c5f563fkauthuserid")]
		public auth_user djangoadminloguserid52fdd58701c5f563fkauthuserid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="django_content_type")]
	public partial class django_content_type
	{
		[PrimaryKey, Identity] public int    id        { get; set; } // integer
		[Column,     NotNull ] public string app_label { get; set; } // character varying(100)
		[Column,     NotNull ] public string model     { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// auth_content_type_id_508cf46651277a81_fk_django_content_type_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="content_type_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<auth_permission> authcontenttypeid508cf46651277a81fkdjangocontenttypeid { get; set; }

		/// <summary>
		/// djan_content_type_id_697914295151027a_fk_django_content_type_id_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="content_type_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<django_admin_log> djancontenttypeid697914295151027afkdjangocontenttypeid { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="django_migrations")]
	public partial class django_migrations
	{
		[PrimaryKey, Identity] public int            id      { get; set; } // integer
		[Column,     NotNull ] public string         app     { get; set; } // character varying(255)
		[Column,     NotNull ] public string         name    { get; set; } // character varying(255)
		[Column,     NotNull ] public DateTimeOffset applied { get; set; } // timestamp (6) with time zone
	}

	[Table(Schema="public", Name="django_session")]
	public partial class django_session
	{
		[PrimaryKey, NotNull] public string         session_key  { get; set; } // character varying(40)
		[Column,     NotNull] public string         session_data { get; set; } // text
		[Column,     NotNull] public DateTimeOffset expire_date  { get; set; } // timestamp (6) with time zone
	}

	[Table(Schema="public", Name="genre")]
	public partial class genre
	{
		[PrimaryKey, NotNull    ] public int    id   { get; set; } // integer
		[Column,        Nullable] public string name { get; set; } // text

		#region Associations

		/// <summary>
		/// movie_genre_genre_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="genre_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<movie_genre> movieidfkeys { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="movie")]
	public partial class movie
	{
		[PrimaryKey, NotNull    ] public int       id                { get; set; } // integer
		[Column,        Nullable] public string    original_language { get; set; } // text
		[Column,        Nullable] public string    original_title    { get; set; } // text
		[Column,        Nullable] public DateTime? release_date      { get; set; } // date
		[Column,        Nullable] public float?    popularity        { get; set; } // real
		[Column,        Nullable] public string    title             { get; set; } // text
		[Column,        Nullable] public float?    vote_average      { get; set; } // real
		[Column,        Nullable] public int?      vote_count        { get; set; } // integer

		#region Associations

		/// <summary>
		/// movie_genre_movie_id_fkey_BackReference
		/// </summary>
		[Association(ThisKey="id", OtherKey="movie_id", CanBeNull=true, IsBackReference=true)]
		public IEnumerable<movie_genre> genreidfkeys { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="movie_genre")]
	public partial class movie_genre
	{
		[PrimaryKey, NotNull] public int id       { get; set; } // integer
		[Column,     NotNull] public int movie_id { get; set; } // integer
		[Column,     NotNull] public int genre_id { get; set; } // integer

		#region Associations

		/// <summary>
		/// movie_genre_genre_id_fkey
		/// </summary>
		[Association(ThisKey="genre_id", OtherKey="id", CanBeNull=false, KeyName="movie_genre_genre_id_fkey", BackReferenceName="movieidfkeys")]
		public genre moviegenregenreidfkey { get; set; }

		/// <summary>
		/// movie_genre_movie_id_fkey
		/// </summary>
		[Association(ThisKey="movie_id", OtherKey="id", CanBeNull=false, KeyName="movie_genre_movie_id_fkey", BackReferenceName="genreidfkeys")]
		public movie moviegenremovieidfkey { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="person")]
	public partial class person
	{
		[PrimaryKey, NotNull    ] public int    id        { get; set; } // integer
		[Column,        Nullable] public string firstname { get; set; } // character varying(255)
		[Column,        Nullable] public string lastname  { get; set; } // character varying(255)
	}

	[Table(Schema="public", Name="play_evolutions")]
	public partial class play_evolutions
	{
		[PrimaryKey, NotNull    ] public int      id            { get; set; } // integer
		[Column,     NotNull    ] public string   hash          { get; set; } // character varying(255)
		[Column,     NotNull    ] public DateTime applied_at    { get; set; } // timestamp (6) without time zone
		[Column,        Nullable] public string   apply_script  { get; set; } // text
		[Column,        Nullable] public string   revert_script { get; set; } // text
		[Column,        Nullable] public string   state         { get; set; } // character varying(255)
		[Column,        Nullable] public string   last_problem  { get; set; } // text
	}

	[Table(Schema="public", Name="schema_migrations")]
	public partial class schema_migrations
	{
		[Column, NotNull] public string version { get; set; } // character varying(255)
	}

	public static partial class TableExtensions
	{
		public static auth_group Find(this ITable<auth_group> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static auth_group_permissions Find(this ITable<auth_group_permissions> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static auth_permission Find(this ITable<auth_permission> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static auth_user Find(this ITable<auth_user> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static auth_user_groups Find(this ITable<auth_user_groups> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static auth_user_user_permissions Find(this ITable<auth_user_user_permissions> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static django_admin_log Find(this ITable<django_admin_log> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static django_content_type Find(this ITable<django_content_type> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static django_migrations Find(this ITable<django_migrations> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static django_session Find(this ITable<django_session> table, string session_key)
		{
			return table.FirstOrDefault(t =>
				t.session_key == session_key);
		}

		public static genre Find(this ITable<genre> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static movie Find(this ITable<movie> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static movie_genre Find(this ITable<movie_genre> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static person Find(this ITable<person> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}

		public static play_evolutions Find(this ITable<play_evolutions> table, int id)
		{
			return table.FirstOrDefault(t =>
				t.id == id);
		}
	}
}
